app:
  port: 8081

database:
  host: postgres-product
  port: 5432
  user: admin
  password: admin
  name: product

redis:
  host: redis
  port: 6379
  password: admin

tracing:
  endpoint: jaeger:4318
  service_name: productfc
  enabled: true

